window.ATIVIDADES_DISPONIVEIS = [
    "Desmontagem do  câmbio banco para inspeção",
    "Desmontagem de Cambio AT9 fim de prova",
    "Desmontagem de câmbio CVT fim de prova",
    "Desmontagem de câmbio AT6 fim de prova",
    "Atualização de câmbio protótipo",
    "Atualização de câmbio EDCT",
    "Desmontagem de câmbio EDCT fim de prova",
    "Substituir câmbio EDCT",
    "Substituir câmbio AT9 aplicação GME",
    "Substituir câmbio AT9 aplicação 2.2 diesel",
    "Substiruir câmbio AT9 aplicação T4",
    "Substituir câmbio AT6",
    "Substituir câmbio CVT",
    "Substituir câmbio C513",
    "Substituir câmbio KP1 MT",
    "Substituir câmbio KP1 AT",
    "Substituir PTU",
    "Substituir RDU",
    "Substituir comando câmbio KP1",
    "Substituir comando câmbio linha jeep",
    "Substituir comando câmbio linha PSA",
    "Substituir comando câmbio linha fiat",
    "Check list carro novo",
    "Check list carro usado",
    "Rodagem de prova de TDOA 4X2",
    "Rodagem de prova de TDOA 4X4",
    "Realizar instrumentação prova TDOA 4X2",
    "Realizar instrumentação prova TDOA 4X4",
    "Realizar Prova de poeira",
    "Realizar prova de lama",
    "Realizar prova guado",
    "Realizar prova de temperatura de óleo câmbio",
    "Realizar prova parking",
    "Preparar veículo para prova de temperatura óleo câmbio",
    "Preparar veículo para prova poeira",
    "Preparar veículo para prova lama",
    "Preparar Veículo para prova parking",
    "Preparar veículo para prova de energy test",
    "Preparar veíuclo para realizar prova de ciclo napole",
    "Preparar veículo para prova de seme eixo",
    "Realizar prova de validação de seme eixo",
    "Preparar câmbio AT9 com central hidraulica do câmbio instrumentada",
    "Preparar veículo para realizar prova de sistema 4X4",
    "Realizar prova para validação de sistema 4X4",
    "Preparar veículo para prova de spunto câmbio",
    "Preparar veículo para prova de balocco",
    "Preparar veículo para realizar prova de medição comando câmbio",
    "Substituição de 04 pneus e balanceamento de roda",
    "Instrumentação com gage componentes diversos",
    "Substituição de pastilha de freio"
];
