window.ATIVIDADES_DISPONIVEIS = [
    "Desmontagem de câmbio em bancada para inspeção",
    "Desmontagem de câmbio AT9 fim de prova",
    "Desmontagem de câmbio CVT fim de prova",
    "Desmontagem de câmbio AT6 fim de prova",
    "Atualização de câmbio protótipo",
    "Atualização de câmbio EDCT",
    "Desmontagem de câmbio EDCT fim de prova",
    "Substituir câmbio EDCT",
    "Substituir câmbio AT9 aplicação GME",
    "Substituir câmbio AT9 aplicação 2.2 diesel",
    "Substituir câmbio AT9 aplicação T4",
    "Substituir câmbio AT6",
    "Substituir câmbio CVT",
    "Substituir câmbio C513",
    "Substituir câmbio KP1 MT",
    "Substituir câmbio KP1 AT",
    "Substituir PTU",
    "Substituir RDU",
    "Substituir comando câmbio KP1",
    "Substituir comando de câmbio linha Jeep",
    "Substituir comando câmbio linha PSA",
    "Substituir comando de câmbio linha Fiat",
    "Check list carro novo",
    "Check list carro usado",
    "Rodagem de prova de TDOA 4X2",
    "Rodagem de prova de TDOA 4X4",
    "Realizar instrumentação prova TDOA 4X2",
    "Realizar instrumentação prova TDOA 4X4",
    "Realizar prova de poeira",
    "Realizar prova de lama",
    "Realizar prova de vau",
    "Realizar prova de temperatura de óleo câmbio",
    "Realizar prova de parking",
    "Preparar veículo para prova de temperatura óleo câmbio",
    "Preparar veículo para prova poeira",
    "Preparar veículo para prova lama",
    "Preparar veículo para prova de parking",
    "Preparar veículo para prova de Energy Test",
    "Preparar veículo para realizar prova de ciclo Napole",
    "Preparar veículo para prova de semi-eixo",
    "Realizar prova de validação de semi-eixo",
    "Preparar câmbio AT9 com central hidráulica do câmbio instrumentada",
    "Preparar veículo para realizar prova de sistema 4X4",
    "Realizar prova para validação de sistema 4X4",
    "Preparar veículo para prova de Spunto do câmbio",
    "Preparar veículo para prova de Balocco",
    "Preparar veículo para realizar prova de medição do comando de câmbio",
    "Substituição de 04 pneus e balanceamento de roda",
    "Instrumentação com gages em componentes diversos",
    "Substituição de pastilhas de freio",
    "Desmontagem do câmbio CVT para retirada de peças para o laboratorio",
    "Descarte de câmbio C513",
    "Levar peças para área de descarte galpão 85",
    "Descarte de câmbio AT6b",
    "Instalação de Control TEC",
    "Carregamento e pesagem de veículos com peso",
    "Preparação de câmbio protótipos",
    "Descarte de pneus",
    "Acompanhar o analista no momento de aquisição de medições de comando de câmbio",
    "Preparação do carro para medição de comando",
    "Preparar veículo para rodagem de prova no ciclo Ama para validação de engrenagens"
].sort((primeira, segunda) => primeira.localeCompare(segunda, "pt-BR"));
